# Generated by Django 2.1.5 on 2019-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='food_default.jpg', upload_to='recipe_pics'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
