# Generated by Django 2.1.5 on 2019-02-17 02:07

from django.db import migrations, models
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0003_recipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='recipe',
            name='authenticityRating',
            field=master_app.models.MinMaxFloat(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealPrepTimeMinutes',
            field=models.IntegerField(default=0, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='overallRating',
            field=master_app.models.MinMaxFloat(default=0),
            preserve_default=False,
        ),
    ]
