# Generated by Django 2.1.5 on 2019-03-31 23:03

from django.db import migrations, models
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_auto_20190216_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealPrepTimeMinutes',
            field=master_app.models.MinMaxFloat(),
        ),
    ]
