# Generated by Django 2.1.7 on 2019-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_auto_20190331_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeCategory',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='authenticityRating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Authenticity Rating (stars) '),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='overallRating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Overall Rating (stars) '),
        ),
    ]
