# Generated by Django 2.1.5 on 2019-04-01 11:52

from django.db import migrations
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0007_auto_20190331_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mealPrepTimeMinutes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_PrepTime_Minutes',
            field=master_app.models.MinMaxFloat(default='5.0'),
        ),
    ]
