# Generated by Django 2.1.7 on 2019-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0008_auto_20190401_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
