# Generated by Django 2.1.5 on 2019-04-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0011_auto_20190401_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vegan'), (2, 'Keto'), (3, 'Paleo'), (4, 'Vegetarian'), (5, 'General')], default=5, verbose_name='Category'),
        ),
    ]
