# Generated by Django 2.1.5 on 2019-04-02 17:24

from django.db import migrations, models
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=master_app.models.MinMaxFloat(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
