# Generated by Django 2.1.7 on 2019-04-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vegan'), (2, 'Keto'), (3, 'Paleo'), (4, 'Vegetarian')], default=3, verbose_name='Category '),
        ),
    ]
