# Generated by Django 2.1.7 on 2019-04-02 23:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0014_auto_20190402_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Overall Rating (stars) ')),
                ('authenticityRating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Authenticity Rating (stars) ')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.Recipe')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipereview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recipereview',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipereview',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecipeReview',
        ),
    ]
