# Generated by Django 2.1.7 on 2019-04-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0015_auto_20190402_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='authenticityRating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Authenticity Rating (stars) '),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Overall Rating (stars) '),
        ),
    ]
