# Generated by Django 2.1.5 on 2019-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0016_auto_20190402_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
