# Generated by Django 2.1.2 on 2019-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0018_auto_20190407_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image2',
            field=models.ImageField(default='food_default.jpg', upload_to='recipe_pics'),
        ),
    ]
