# Generated by Django 2.1.5 on 2019-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0019_recipe_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='food_default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image2',
            field=models.ImageField(blank=True, default='food_default.jpg', upload_to=''),
        ),
    ]
