# Generated by Django 2.1.5 on 2019-04-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0022_auto_20190409_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(default='food_default.jpg', upload_to='recipe_pics'),
        ),
    ]
